### ISSUE TITLE
Could not load assembly 'System.Reactive.Linq, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Perhaps it doesn't exist in the Mono for Android profile?

### ISSUE THREAD

**Issue by GHofman93** [step-up-labs/firebase-database-dotnet#148] opened 2018-06-24 10:43 UTC
Dear everyone reading,

I am at lost for words that before me this exception is thrown. Can someone point me in the right direction for resolving this issue?

It's a visual studio xamarin (native) android project, with min. android 7 and also targets 7.
The moment I install FirebaseDatabase.Net this error pops up. 

I have tried to
- reinstall all the System.Reactive packages, rebuild
- delete the packages folder, and rebuild
- ^ again with deleting the Bin/debug folder, and rebuild

Thank you kindly

**Comment by bezysoftware** [comment] 2018-09-03 12:54
Duplicate of #155

**Closed by bezysoftware** 2018-09-03 12:54 UTC
