### ISSUE TITLE
Listening to List is duplicating values

### ISSUE THREAD

**Issue by bdbehrho** [step-up-labs/firebase-database-dotnet#180] opened 2018-12-06 04:11 UTC
I have an Object with a list of integers. I want to listen to the list so I can see when a value is added. The Updates come in at the right time, but every time the list receives an update, it has duplicated all of the values.

(Initial setup, list exists and has 10 values)
1. Start listening to the list
2. Add a value, I receive an updated list with 11 values
3. Add another value, I receive an updated list with 23 values, the 12 were appended instead of just the 1

Example Code:
```
public class ParentObject {
  public List<int> Values {get; set;} = new List<int>();
}

public async void ListenAndUpdate() {
    // Assume a valid ParentObject exists with this key at collection 'parentobjects'
    var testId = "testkey";

    var parentObject = await GetSingle(testId);

    // start listening for changes to "testkey"
    ListenForChangesToValues(testId);

    for(int i = 0; i < 10; i++)
    {
        parentObject.Values.Add(1);
        await Update(testId, parentObject);
        Thread.Sleep(5000);
    }
}


public void ListenForChangesToValues(string id){
    firebaseClient
        .Child("parentobjects")
        .Child(id)
        .Child(nameof(ParentObject.Values))
        .AsObservable<List<int>>(elementRoot: nameof(ParentObject.Values))
        // The first time this comes back, the length is correct, subsequent times it has duplicated values
        .Subscribe(newValues => Console.WriteLine(newValues.Object.Count));
}

public async Task Update(string id, ParentObject item) {
    await firebaseClient
        .Child("parentobjects")
        .Child(id)
        .PutAsync<ParentObject>(item);
}

public async Task<ParentObject> GetSingle(string id){
    var model = await firebaseClient
        .Child("parentobjects")
        .Child(id)
        .OnceSingleAsync<ParentObject>();
    return model;
}
```
It is worth noting that the values are not being duplicated in firebase, only the returned values passed into the Subscribe Action. Seems like a bug, but possible I'm just misusing the library.

Thanks for your time! Overall a huge fan of this project.

**Comment by kormemis** [comment] 2018-12-19 23:32
got same issue , subscribe function receive multiple same values even one thing changed. I expect to listen only one value by one change on the firebase

**Comment by cabauman** [comment] 2018-12-22 09:10
That's odd. This behaviour was supposedly fixed [here](https://github.com/step-up-labs/firebase-database-dotnet/commit/9a464c418d6de6036aadf2386b67ed04c50dee56), but I can confirm your findings because I tried it out myself. In the [FirebaseCache](https://github.com/step-up-labs/firebase-database-dotnet/blob/9652f249b9c167f1e9ed17664d0c22e67cc872f1/src/Firebase/Streaming/FirebaseCache.cs#L153) `JsonConvert.PopulateObject(data, obj, this.serializerSettings);` still appends to the list instead of replacing it.

Playing around a bit, I did end up getting the correct list behavior. I don't know if I'm overlooking something or not, but this condition seems unnecessary:

```
if ((valueType.GetTypeInfo().IsPrimitive || valueType == typeof(string)) && primitiveObjSetter != null)
{
    // handle primitive (value) types separately
    primitiveObjSetter(targetObject);
}
else
{
    JsonConvert.PopulateObject(data, obj, this.serializerSettings);
}
```

because in my tests `primitiveObjSetter(targetObject);` works just fine for lists, dictionaries, and other non-primitive objects.

And as a side note, I don't see the purpose of this line `this.dictionary[pathElements[0]] = this.dictionary[pathElements[0]];` (just assigning to itself??) so I removed that line too. I'll make a PR if Bezy validates my logic.

**Closed** 2018-12-25 08:43 UTC
